[package]
name = "fcnn"
version = "0.1.0"
authors = ["jmpargana <jmpargana@stud.uni-frankfurt.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ndarray = "0.13.0"
# rayon = "1.3.0"

